# https://taskfile.dev
# goup-util - Cross-platform hybrid app build tool
#
# All tasks are namespaced. Run 'task --list' to see available namespaces:
#
#   dev:*          Development (build, test, setup, SDKs)
#   run:*          Run examples directly (go run .)
#   build:*        Build examples for platforms
#   screenshot:*   Screenshot capture (requires CGO)
#   ci:*           CI/CD and release
#   utm:*          UTM VM automation
#   src:*          .src dependency management
#   docs:*         Documentation
#
# Quick start:
#   task dev:demo     Build and run hybrid-dashboard
#   task dev:build    Build goup-util
#   task dev:test     Run tests
#
version: '3'

# Global vars - available to all included taskfiles
vars:
  GOUP: go run .
  BASIC_EXAMPLE: examples/gio-basic
  WEBVIEWER_EXAMPLE: examples/gio-plugin-webviewer
  HYPERLINK_EXAMPLE: examples/gio-plugin-hyperlink
  HYBRID_EXAMPLE: examples/hybrid-dashboard
  HYBRID_SCHEMES: "hybrid,hybriddashboard"

includes:
  dev:
    taskfile: ./Taskfile.dev.yml
  run:
    taskfile: ./Taskfile.run.yml
  build:
    taskfile: ./Taskfile.build.yml
  screenshot:
    taskfile: ./Taskfile.screenshot.yml
  ci:
    taskfile: ./Taskfile.ci.yml
  utm:
    taskfile: ./Taskfile.utm.yml
    optional: true
  src:
    taskfile: .src/Taskfile.yml
    dir: .src
    optional: true
  docs:
    taskfile: docs/Taskfile.yml
    dir: docs
    optional: true

tasks:
  default:
    desc: Show available task namespaces
    silent: true
    cmds:
      - |
        echo "goup-util task namespaces:"
        echo ""
        echo "  dev:*          Development (build, test, setup)"
        echo "  run:*          Run examples (go run .)"
        echo "  build:*        Build examples for platforms"
        echo "  screenshot:*   Screenshots (capture, appstore)"
        echo "  ci:*           CI/CD (build, release)"
        echo "  utm:*          UTM VMs (start, stop, exec)"
        echo "  src:*          Dependencies (.src management)"
        echo "  docs:*         Documentation"
        echo ""
        echo "Quick start:"
        echo "  task dev:demo          Build & run hybrid-dashboard"
        echo "  task dev:build         Build goup-util"
        echo "  task run:hybrid        Run example directly"
        echo ""
        echo "Run 'task --list' for all tasks"
