name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Build goup-util with obfuscation
      run: |
        echo "Building with self system (auto-installs garble)..."
        go run . self build --obfuscate

    - name: Verify JSON output
      run: |
        echo "Testing self version command..."
        ./.dist/goup-util-darwin-arm64 self version | jq .

    - name: List built binaries
      run: |
        echo "Built binaries:"
        ls -lh .dist/

    - name: Upload all artifacts
      uses: actions/upload-artifact@v4
      with:
        name: goup-util-all-platforms
        path: .dist/*
