name: Examples

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-examples:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        example: [gio-basic, gio-plugin-hyperlink, gio-plugin-webviewer]
        platform: [macos, windows, android]
        exclude:
          - os: ubuntu-latest
            platform: macos
          - os: windows-latest
            platform: macos
          - os: windows-latest
            platform: android
          - os: macos-latest
            platform: android
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.0'
    
    - name: Build goup-util
      run: go build -o goup-util .
    
    - name: Build example
      run: ./goup-util build ${{ matrix.platform }} examples/${{ matrix.example }}