name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    # - name: Run tests
    #   run: go test ./...
    
    - name: Build all platforms
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X main.version=${GITHUB_REF#refs/tags/}" -o dist/goup-util-linux-amd64 .
        GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w -X main.version=${GITHUB_REF#refs/tags/}" -o dist/goup-util-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w -X main.version=${GITHUB_REF#refs/tags/}" -o dist/goup-util-darwin-arm64 .
        GOOS=windows GOARCH=amd64 go build -ldflags="-s -w -X main.version=${GITHUB_REF#refs/tags/}" -o dist/goup-util-windows-amd64.exe .
        GOOS=windows GOARCH=arm64 go build -ldflags="-s -w -X main.version=${GITHUB_REF#refs/tags/}" -o dist/goup-util-windows-arm64.exe .
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/goup-util-*
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}